### ISSUE TITLE
Rename the main development branch from master to main

### ISSUE THREAD

**Issue by willklein** [Workday/canvas-kit#1093]
## ⚡️ Improvement

`master` => `main`. Let's make the switch post-v5. 

## Motivation

Move from an antiquated and even harmful term to something more semantically meaningful. `master` is at best jargon-based, and newer developers going forward will be more and more accustomed to main.

## Example

[main is now the default branch for new repos on GitHub](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)
[github/renaming (guidance)](https://github.com/github/renaming/)

## Todo

- [ ] Catalog CI configuration to update
- [ ] Catalog references in the repo
- [ ] Investigate how any design site links may break
- [ ] Update in-flight PRs
- [ ] Notify everyone in our internal Slack
- [ ] What else?

**Comment by jaclynjessup** [comment]
Open question - What happens with everyones forked repo?
