### ISSUE TITLE
Promote Toast in Preview to Main in v9

### ISSUE THREAD

**Issue by willklein** [Workday/canvas-kit#1935]
## 💡 Suggestion

The Toast in Preview is being used and has proven to solve problems recently raised on the component that is in Main

### Acceptance Criteria

- [ ] Update the upgrade guide
- [ ] Figure out what migration path looks like
- [ ] Remove main Toast, tests, etc
- [ ] Promote Preview Toast
- [ ] Review our quality checks (design, a11y, documentation, engineering, developer experience) 

```[tasklist]
### Tasks
- [ ] #2060 
- [ ] #2062 
```
