### ISSUE TITLE
Modify Depth Tokens for v9

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1948]
## ⚓️ Epic
The depth tokens we released in v7 are too bold for web applications and should be modified to improve the visual design. 
### Product
   This work will include:

- [ ] Making the depth updates to the Canvas depth tokens
- [ ] Modifying components to utilize new depth token values, if applicable
- [ ] Creating a code mod to handle help teams switch over to the new depth token values
- [ ] Testing the new depth tokens and code mod for it with product teams

  ### Technical
  Requirements from a technical stand point - ie will this be a compound component

  ### Design
  Requirements from the design team

  ### A11Y
  requirements from the accessibility 

## Scope
Define what is a must-have for launch (in-scope) and what will not happen for launch (out-of-scope)

  ### In-scope
  - Make a list
  - of things that are
  - a MUST for launching

  ### Out-of-scope
  - Make a list
  - of things that are
  - a NOT needed launching

## Breakdown

- [ ] Link issues 
- [ ] to this epic
- [ ] by using the issue #

**Comment by mannycarrera4** [comment]
There's something we need to consider and I think we should support. When talking to Matt, we should consider a blend mode for depth values.

Example: https://codepen.io/karunpant/pen/jdpxKM

This adds an extra element.

Example of box shadow on the card (which is what we have now)
https://codesandbox.io/s/cool-cookies-1ig31r?file=/src/App.tsx

I still need to investigate, but if we could apply a blend mode on a css property that would be ideal.

Adding an extra element gets tricky when dealing with popups and modal and z index fiascos.
