### ISSUE TITLE
Spike: Bump react-virtual to the lastest v3

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#2663]
## 💡 Suggestion

`react-virtual` v2 seems to work fine with React 18, but it has a lot of noisy console warnings. We should bump to the latest v3 which supports React 18 by default. This might be something we can do in v10 as a patch, but it might have to happen in v11 if there are breaking changes. `react-virtual` doesn't have a changelog or upgrade guide (that I could find), just [this commit log](https://github.com/TanStack/virtual/compare/v2.10.4...v3.2.0). We'll need to work through the changes carefully so we don't break anything.
```[tasklist]
### Tasks
- [ ] Explore how much effort this will take
- [ ] Will this be a breaking change?
- [ ] Can this go in a minor of v11?
```

**Comment by mannycarrera4** [comment]
React Virtual -> TanStack React Virtual update
- size gets renamed to count
- parentRef changes to getScrollEmenet
```tsx
// OLD API (Current Canvas Kit)
const oldAPI = useVirtual({
  size: items.length,
  parentRef: containerRef,
  // ...
});

// NEW API (TanStack)  
const newAPI = useVirtual({
  count: items.length,
  getScrollElement: () => containerRef.current,
  // ...
});
```
- We can update to tan stack while still providing backwards compatibility
update useVirtual to add the new properties and deprecate the old ones
