### ISSUE TITLE
❗Component Testing Checklist

### ISSUE THREAD

**Issue by lychyi** [Workday/canvas-kit#286]
# Test Coverage Checklist

Reference to PR that removed snapshots (#259) for reference when re-writing tests that we blew away from this.

## Blockers
- ~~Storybook does not load into IE11~~
- ~~Storybook 5.2 gets merged (#267) for MDX - _Format for visual tests will be reconsidered after Storybook 5.2 gets merged_~~

## Guides
[Testing philosophy and guidelines](https://github.com/Workday/canvas-kit/blob/master/TESTING.md)

## React
For these components, we'll have to ensure we have adequate coverage for unit tests (Jest, React Testing Library) and specification/e2e tests (Cypress).

### Canvas Kit React
- [x] @workday/canvas-kit-react-action-bar (#1396)
- [x] @workday/canvas-kit-react-avatar (#614)
- [ ] @workday/canvas-kit-react-banner
- [x] @workday/canvas-kit-react-button (#468)
- [x] @workday/canvas-kit-react-card (#708)
- [x] @workday/canvas-kit-react-checkbox (#372)
- [x] @workday/canvas-kit-react-color-picker (#407)
- [ ] @workday/canvas-kit-react-common
- [ ] @workday/canvas-kit-react-core
- [ ] @workday/canvas-kit-react-fonts
- [x] @workday/canvas-kit-react-form-field (#482)
- [ ] @workday/canvas-kit-react-icon
- [x] @workday/canvas-kit-react-layout (#1027)
- [ ] @workday/canvas-kit-react-loading-animation
- [x] @workday/canvas-kit-react-modal (specs #184)
- [x] @workday/canvas-kit-react-popup (#600)
- [x] @workday/canvas-kit-react-radio (#381)
- [x] @workday/canvas-kit-react-select (#412)
- [x] @workday/canvas-kit-react-skeleton (#720)
- [x] @workday/canvas-kit-react-status-indicator (#692)
- [x] @workday/canvas-kit-react-switch (#386)
- [ ] @workday/canvas-kit-react-table
- [x] @workday/canvas-kit-react-text-area (#394)
- [x] @workday/canvas-kit-react-text-input (#390)
- [x] @workday/canvas-kit-react-toast (#584 )
- [x] @workday/canvas-kit-react-tooltip (#528)

### Canvas Kit Labs React
- [x] @workday/canvas-kit-labs-react-combobox (#535)
- [x] @workday/canvas-kit-labs-react-menu (#812)

### Canvas Kit Preview React
- [x] @workday/canvas-kit-react-preview-side-panel (#866)

### Canvas Kit Labs React (WIP)
- [x] @workday/canvas-kit-labs-react-pagination (#301)
- [ ] @workday/canvas-kit-labs-react-slider

## CSS
For these components, visual regression (Storybook and Chromatic) and _sometimes_ specification/e2e tests (Cypress).

**Comment by jpante** [comment]
Converting this to a Milestone.

**Comment by jaclynjessup** [comment]
Closing in favor of #1773 to investigate current testing gaps
