### ISSUE TITLE
Component Refactoring to Use CSS Tokens

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#2953]
## ⚓️ Epic
This epic covers all the remaining work required to refactor Canvas components.

## Requirements
- Utilize the cs prop
- Use the new system and brand level tokens

## Breakdown

- [ ] https://github.com/Workday/canvas-kit/issues/2778
- [ ] https://github.com/Workday/canvas-kit/issues/2777
- [ ] https://github.com/Workday/canvas-kit/issues/2393
