### ISSUE TITLE
Update Logos and Dubs

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#3010]
## ⚓️ Epic
Update Workday logos and dubs.

## Requirements

- All instances of Workday logos and dubs are updated

## Scope
- CKR
- CK owned artifacts

## Breakdown

- [ ] Set up and add the new logos + dubs to a new S3 bucket
- [ ] Update CKR dub and logo references
- [ ] Update logo in site footer
- [ ] Update logo and dub reference links
