### ISSUE TITLE
Canvas Kit 4.0

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#483]
## 🚀 Feature Proposal

We're starting to work on some 4.0 changes. We want to capture them here for anyone to reference. All changes will go into the `prerelease/v4` branch. Beta builds will be available under the `4.0.0-beta.*` version.

## Motivation

There are several refactors/breaking changes we plan to make to our repo. To account for these, will be bumping the major version in the near future.

## Changes

- [x] Modal (z-index/React portal changes, visual breaking change #419)
- [ ] React Portals for all popups (modal, tooltip, toast, popup) (#419, #528)
- [x] Button Refactor (types, interfaces, hooks, officially leaving <= React 16.7 behind #471)
- [x] Rename `IconButtonToggleGroup` to `SegmentedControl` (#505)
- [x] Popper v2 upgrade (#528)
- [x] Typescript 3.7 or 3.8 (w/ downlevel-dts) (https://github.com/Workday/canvas-kit/pull/533)
- [x] Remove `tslint` dependency (https://github.com/Workday/canvas-kit/pull/533)
- [ ] Fix Storybook 6.0 CRA warning (#533)
- [ ] Fix `SyntheticEvent` type usage (https://github.com/Workday/canvas-kit/pull/499)
- [ ] Adjust `InputProvider` to use document.body with a configurable container (to be compatible with React Portal updates)
- [ ] Promote `useTheme`, `styled` out of labs, and replace `focusRing` with `themedFocusRing`
- [ ] `TextButton` and `Hyperlink` updates

### Considerations
- Emotion 11?
- Any labs components we want to move to GA? (ensure we add to bundle modules)
- Type hierarchy updates (#319 )? 
- More to come...

**Comment by anicholls** [comment]
Closing in favor of milestone: https://github.com/Workday/canvas-kit/milestone/2
