### ISSUE TITLE
Color Picker Enhancements

### ISSUE THREAD

**Issue by jpante** [Workday/canvas-kit#921]
## 🐛 Bug Report

There are a number enhancements for the color picker to improve the API and address a11y issues.

See below

- [ ] https://github.com/Workday/canvas-kit/issues/701 - Aria labels for color picker swatches 
- [ ] https://github.com/Workday/canvas-kit/issues/898 - Hitting enter key should submit color in custom hex color input

### Other CP Issues
- [ ] https://github.com/Workday/canvas-kit/issues/833 - Color Picker: Move to a more explicit api for rows and columns of the swatchbook
- [ ] https://github.com/Workday/canvas-kit/issues/886 - Check mark on custom hex input swatch

**Comment by jaclynjessup** [comment]
Closing in favor of #1852
